"""Generate config/rosters.example.yaml by snake-drafting the ranked pool.

The real config/rosters.yaml is gitignored because it names real people, so the
repo needs a stand-in that's realistic enough to exercise the whole pipeline --
twelve legal rosters, no duplicated players, everyone accounted for. Hand-typing
120 players and keeping them consistent is not a good use of anyone's afternoon.

Team names are made up. The draft is need-aware rather than pure best-available
so nobody ends up with two quarterbacks and nobody ends up with none.

Run from the repo root:

    python scripts/make_example_rosters.py
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from fpr import config  # noqa: E402
from fpr.adapters import raw_csv  # noqa: E402
from fpr.core.consensus import build  # noqa: E402
from fpr.core.lineup import Roster, build_optimal  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "config" / "rosters.example.yaml"

TEAM_NAMES = [
    "Gridiron Gremlins",
    "Couch Potatoes",
    "Turf Toe Titans",
    "Play Action Heroes",
    "Hurry Up Offense",
    "Pylon Pirates",
    "Blitz Brigade",
    "Screen Door Slammers",
    "Audible Anarchy",
    "Two Minute Warning",
    "Hail Mary Hooligans",
    "Fourth and Forever",
]

HEADER = """\
# Example rosters -- copy to config/rosters.yaml and replace with your league.
# config/rosters.yaml is gitignored because it names real people.
#
# GENERATED by scripts/make_example_rosters.py. Team names are invented; the
# players are snake-drafted off the committed rankings so all twelve rosters
# are legal and nobody appears twice. Edit the script, not this file.
#
# Slot keys are position groups, not display slots. Which back ends up RB1 is
# decided by value at runtime, so the order here doesn't matter.
"""


def snake_order(teams: int, rounds: int):
    for rnd in range(rounds):
        order = range(teams) if rnd % 2 == 0 else reversed(range(teams))
        yield from order


def draft(players, teams: int, rounds: int):
    """Need-aware snake draft. Returns a list of rosters, best-ranked first."""
    pool = list(players)
    squads: list[list] = [[] for _ in range(teams)]

    def count(squad, position):
        return sum(1 for p in squad if p.position == position)

    for pick, team in enumerate(snake_order(teams, rounds)):
        if not pool:
            break
        squad = squads[team]
        picks_left = rounds - (pick // teams)

        # One QB per team, no more. Everyone needs one, so if a team is running
        # out of picks it takes a quarterback whether it wants to or not.
        has_qb = count(squad, "QB") >= 1
        needs = []
        if not has_qb:
            needs.append("QB")
        for position, minimum in (("RB", 4), ("WR", 4), ("TE", 2)):
            if count(squad, position) < minimum:
                needs.append(position)

        forced = len(needs) >= picks_left

        def ok(player, has_qb=has_qb, needs=needs, forced=forced):
            if player.position == "QB" and has_qb:
                return False
            return player.position in needs if forced else True

        choice = next((p for p in pool if ok(p)), pool[0])
        pool.remove(choice)
        squad.append(choice)

    return squads


def to_roster(squad, table, cfg, team_name) -> Roster:
    """Group a drafted squad the way a platform adapter would return it."""
    lineup = build_optimal(team_name, Roster(bench=[p.name for p in squad]), table, cfg)
    started = {p.name for slot, p in lineup.players.items() if slot in cfg.starter_slots}
    return Roster(
        qb=[lineup["QB"].name],
        rb=[lineup["RB1"].name, lineup["RB2"].name],
        wr=[lineup["WR1"].name, lineup["WR2"].name],
        te=[lineup["TE"].name],
        flex=[lineup["FLEX1"].name, lineup["FLEX2"].name],
        bench=[p.name for p in squad if p.name not in started],
    )


def dump(rosters: dict[str, Roster]) -> str:
    lines = [HEADER, "teams:"]
    for team, roster in rosters.items():
        lines.append(f"  {team}:")
        for group in ("qb", "rb", "wr", "te", "flex", "bench"):
            names = ", ".join(getattr(roster, group))
            lines.append(f"    {group}: [{names}]")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    cfg = config.load(REPO / "config" / "league.yaml")
    table = build(raw_csv.load(REPO / "raw_rankings.csv"), cfg)
    ranked = table.ordered()

    rounds = -(-len(ranked) // cfg.teams)  # ceiling, so nobody is left undrafted
    squads = draft(ranked, cfg.teams, rounds)

    rosters = {
        name: to_roster(squad, table, cfg, name)
        for name, squad in zip(TEAM_NAMES, squads, strict=True)
    }

    drafted = [p for roster in rosters.values() for p in roster.all_players()]
    assert len(drafted) == len(set(drafted)), "a player was drafted twice"
    print(f"{len(drafted)} of {len(ranked)} players across {len(rosters)} teams")

    OUT.write_text(dump(rosters), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
